In [9]:
import numpy as np
B=np.array([[4],[5],[6]])
A=np.array([[1,2,3]])
print(B)
print(A)

[[4]
 [5]
 [6]]
[[1 2 3]]


In [10]:
import numpy as np
np.arange(-2,2,5)

array([-2])

In [14]:
import numpy as np
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40]) 
corrected_temperature = temperature + 2
print(corrected_temperature)
fahrenheit = (9/5) * corrected_temperature + 32
print(fahrenheit)
above_32 = corrected_temperature[corrected_temperature > 32]
print(above_32)
count = np.sum(corrected_temperature > 32)
print(count)

[27 30 33 37 40 29 35 42]
[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
[33 37 40 35 42]
5


In [15]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])
print("Total steps:", np.sum(steps))
print("Mean steps:", np.mean(steps))
print("Maximum:", np.max(steps))
print("Minimum:", np.min(steps))
print("Total for each day:", np.sum(steps, axis=0))
print("Total for each user:", np.sum(steps, axis=1))
print("Maximum index:", np.argmax(steps))
print("Maximum position:", np.unravel_index(np.argmax(steps), steps.shape))

Total steps: 84200
Mean steps: 7016.666666666667
Maximum: 9500
Minimum: 4500
Total for each day: [26500 27300 30400]
Total for each user: [18300 24500 14400 27000]
Maximum index: 11
Maximum position: (np.int64(3), np.int64(2))


In [16]:
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])
print("Original:", original)

subset = original[1:5]
print("Subset:", subset)

subset[0] = 999
print("After modifying subset:")
print("Original:", original)
print("Subset:", subset)

original = np.array([1, 2, 3, 4, 5, 6])
copied = original[1:5].copy()
copied[0] = 500

print("\nAfter modifying copied array:")
print("Original:", original)
print("Copied:", copied)

matrix = np.arange(1, 13).reshape(3, 4)
print("\n3x4 Matrix:")
print(matrix)

print("\nFirst row:", matrix[0, :])
print("Last row:", matrix[-1, :])
print("Second column:", matrix[:, 1])
print("Rows 1-2 and columns 2-3:")
print(matrix[1:3, 2:4])

flat = matrix.flatten()
rav = matrix.ravel()

print("\nFlatten:", flat)
print("Ravel:", rav)

rav[0] = 100
print("\nAfter modifying ravel:")
print("Ravel:", rav)
print("Matrix:")
print(matrix)

flat[0] = 500
print("\nAfter modifying flatten:")
print("Flatten:", flat)
print("Matrix:")
print(matrix)

print("\nShape:", matrix.shape)
print("ndim:", matrix.ndim)
print("Size:", matrix.size)
print("dtype:", matrix.dtype)

Original: [1 2 3 4 5 6]
Subset: [2 3 4 5]
After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]

After modifying copied array:
Original: [1 2 3 4 5 6]
Copied: [500   3   4   5]

3x4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]

Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel:
Ravel: [100   2   3   4   5   6   7   8   9  10  11  12]
Matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

After modifying flatten:
Flatten: [500   2   3   4   5   6   7   8   9  10  11  12]
Matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

Shape: (3, 4)
ndim: 2
Size: 12
dtype: int64


In [17]:
import numpy as np
y = np.array([40, 65, 30, 85])

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
print("Shape:", X.shape)
print("Dimensions:", X.ndim)

print("\nX.T:")
print(X.T)

XtX = X.T @ X
print("\nX.T @ X:")
print(XtX)

inverse = np.linalg.inv(XtX)
print("\nInverse:")
print(inverse)

beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("\nBeta coefficients:")
print(beta)

new_user = np.array([5, 40, 7])
prediction = new_user @ beta

print("\nPredicted assistance score:", prediction)

Shape: (4, 3)
Dimensions: 2

X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

Beta coefficients:
[-0.15921454  0.14083853 10.06302242]

Predicted assistance score: 75.27862544779018
