In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
b=a+2
c=a*3
print(a)
print(b)
print(c)

[1 2 3 4 5]
[3 4 5 6 7]
[ 3  6  9 12 15]


In [2]:
import numpy as np

arr=np.array([1,2,3,6,4,5])
rev=arr[::-1]
print(rev)

x=np.array([1,2,3,4,5,1,2,1,1,1])
vals,counts=np.unique(x,return_counts=True)
mf=vals[np.argmax(counts)]
idx=np.where(x==mf)
print(mf,idx)

y=np.array([1,1,1,2,3,4,2,4,3,3])
vals,counts=np.unique(y,return_counts=True)
mf=vals[np.argmax(counts)]
idx=np.where(y==mf)
print(mf,idx)

[5 4 6 3 2 1]
1 (array([0, 5, 7, 8, 9]),)
1 (array([0, 1, 2]),)


In [6]:
import numpy as np
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


In [7]:
import numpy as np

Siya=np.linspace(10,100,25)

print(Siya.ndim)
print(Siya.shape)
print(Siya.size)
print(Siya.dtype)
print(Siya.nbytes)

t=Siya.reshape(25,1)
print(t)

print(Siya.T)

1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [9]:
import numpy as np

ucs420_Siya = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:",ucs420_Siya)

print("Mean:", np.mean(ucs420_Siya))
print("Median:", np.median(ucs420_Siya))
print("Maximum:", np.max(ucs420_Siya))
print("Minimum:", np.min(ucs420_Siya))
print("Unique elements:", np.unique(ucs420_Siya))

# Reshape to 4 rows and 3 columns
reshaped_ucs420_Siya = ucs420_Siya.reshape(4, 3)
print("Reshaped Array:",reshaped_ucs420_Siya)

# Resize to 2 rows and 3 columns
resized_ucs420_Siya = np.resize(ucs420_Siya, (2, 3))
print("Resized Array:",resized_ucs420_Siya)

Original Array: [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array: [[10 20 30]
 [40 50 60]]
